### PR TITLE
Added money intergration

### PR DESCRIPTION
**Pull request by d3fc0n6**
money

### CODE REVIEW

**Review by aUniqueUser — APPROVED** [review]

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
Yea.... No.

**Comment by BenCat07** [comment]
sad

**Comment by BenCat07** [comment]
i'll make a branch

**Comment by TotallyNotElite** [comment]
Nah you wont

**Comment by aUniqueUser** [comment]
sad

**Comment by Snephanie** [comment]
https://github.com/nullworks/cathook/blob/master/src/visual/fidgetspinner.cpp

**Comment by leKamikaze1** [comment]
@TotallyNotElite don't be a pp
!!!

**Pull request closed without merging**
