### PR TITLE
fix ld library path being wrong

### PR DESCRIPTION
**Pull request by BenCat07**
oh also semicolon

### CODE REVIEW

**Review by TotallyNotElite — CHANGES_REQUESTED** [review]
This assumes the local user uses the steam runtime, which is not always the case. For example that's not true for me, my steam runtime was never installed because I've been using native since day 1

**Comment by TotallyNotElite** [comment]
You should probably make the steam runtime execute tf2 directly, see https://github.com/ValveSoftware/steam-runtime#using-a-steam-runtime

**Comment by BenCat07** [comment]
> This assumes the local user uses the steam runtime, which is not always the case. For example that's not true for me, my steam runtime was never installed because I've been using native since day 1

This won't break anything, but it will however use runtime > native libraries. This pull request is just to fix support for steam-runtime, making it dynamically support whatever runtime you use would be quite a big task, and not possible even with what you commented, since that implies the user is already using steam-runtime and not steam-native, so it just leads back to the same issue.

**Comment by TotallyNotElite** [comment]
Just did this the way I like it.

**Pull request closed without merging**
