### PR TITLE
Don't use a non-functional network interface in firejail

### PR DESCRIPTION
**Pull request by delimeats-ch**

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
This PR breaks core functionality. Additionally, Debian Linux is not supported.

**Comment by delimeats-ch** [comment]
This isn't related to Debian. Cathook and catbot-setup et al. all work fine, with the exception of firejail instances not terminating smoothly, though I cannot verify whether it works on other distributions.

I hastily misinterpreted the firejail --help output. The man page seems to suggest that --net=some_interface will give containers their own MAC and IP address. On networks with MAC address whitelisting, this will not work out of the box. The old netns behavior may be more desirable in this case. I might make a fork for it or something.

**Comment by delimeats-ch** [comment]
Here's an up-to-date fix for anyone who wants to use the old netns stuff: https://github.com/delimeats-ch/cathook-ipc-web-panel/tree/netns-rollback

**Comment by delimeats-ch** [comment]
I did confirm that --net will give containers their own MAC and thus IP address. If you have a firewall blocking this sort of thing, you can use network namespacing to masquerade the container traffic as your own.

**Pull request closed without merging**
